#!/bin/sh

exec > /dev/null 2>&1

PLAYER_STATUS=$(playerctl status)
PLAYER=$(swaymsg -t get_tree | grep -q '"app_id": "chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Default"' && echo "Running" || echo "Not running")

if [ "$PLAYER_STATUS" = "Playing" ]; then
	if [ $PLAYER = "Running" ]; then
		swaylock -f
	fi
else
	swaylock -f
fi
