#!/bin/bash

source $HOME/.config/sway/scripts/variables

FULL_ICON_DIR="$ICON_DIR/32x32/symbolic/status"

wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

MUTED=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -o '\[MUTED\]')

if [ -n "$MUTED" ]; then
	icon="$FULL_ICON_DIR/audio-volume-muted-symbolic.svg"
	notify-send "" "Audio device muted." \
			-a "System" \
			-u normal \
			-i "file://$icon"
else
	icon="$FULL_ICON_DIR/audio-volume-high-symbolic.svg"
	notify-send "" "Audio device unmuted." \
		-a "System" \
		-u normal \
		-i "file://$icon"
		fi
