set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g focus-events on
set -g mode-keys vi
set -a terminal-features "xterm-256color:RGB"

set -g status-position top
set -g status-style bg=default
set -g status-justify absolute-centre
set -g status-left "#S"
set -g status-left-style bold
set -g status-right ""
set -g window-status-current-style bold

set -g pane-border-style fg=#1f1f1f
set -g pane-active-border-style fg=#1f1f1f
set -g popup-border-style fg=#1f1f1f
set -g menu-border-style fg=#1f1f1f

unbind C-b
set -g prefix M-space

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

unbind Left
unbind Down
unbind Up
unbind Right
unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind \"
unbind \%
bind V splitw
bind v splitw -h
